In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense,Dropout
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler, RobustScaler

Using TensorFlow backend.


### Loading the dataset

In [2]:
df=pd.read_csv("training_set.csv")
df.dropna()

X=df[['X1','X2','X3','X4','X5','X6','X7','X8','X9','X10','X11','X12','X13','X14','X15','X16','X17','X18','X19','X20','X21','X22','X23','X24','X25','X26','X27','X28','X29','X30','X1','X32','X33','X34','X35','X36','X37','X38','X39','X40','X41','X42','X43','X44','X45','X46','X47','X48','X49','X50','X51','X52','X53','X54','X55','X56','X57']]
# df.head()
# X.head()
y=df['Y']
# y.head()

X.shape
# y.shape

(3910, 57)

### Pre-processing of the data using Min-Max Scaler

In [3]:
# scaler = MinMaxScaler()
# X=scaler.fit_transform(X,y)


### Splitting the data in training and testing set

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

### Feature selection 

In [5]:
from sklearn.datasets import load_digits
from sklearn.feature_selection import SelectKBest, chi2

feature_select=SelectKBest(chi2, k=20)
X_train_new = feature_select.fit_transform(X_train, y_train)
print(X_train_new.shape)
# X_train_new

(3128, 20)


In [6]:
X_test_new = feature_select.transform(X_test)
X_test_new.shape

(782, 20)

### Building the model

In [7]:
model=Sequential()
model.add(Dense(128,input_dim=20,activation='sigmoid'))
model.add(Dropout(0.5))
model.add(Dense(64,activation='sigmoid'))
model.add(Dropout(0.5))
model.add(Dense(1,activation='sigmoid'))

model.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
#for binary classification softmax is same as sigmoid

### Learning of model on traning set

In [8]:
model.fit(X_train_new, y_train, epochs=100)

Epoch 1/100
3128/3128 [==============================] - 0s 127us/step - loss: 0.6724 - accuracy: 0.5943
Epoch 2/100
3128/3128 [==============================] - 0s 46us/step - loss: 0.5626 - accuracy: 0.6969
Epoch 3/100
3128/3128 [==============================] - 0s 53us/step - loss: 0.4729 - accuracy: 0.7689
Epoch 4/100
3128/3128 [==============================] - 0s 47us/step - loss: 0.4177 - accuracy: 0.8107
Epoch 5/100
3128/3128 [==============================] - 0s 46us/step - loss: 0.3768 - accuracy: 0.8290
Epoch 6/100
3128/3128 [==============================] - 0s 50us/step - loss: 0.3507 - accuracy: 0.8504
Epoch 7/100
3128/3128 [==============================] - 0s 49us/step - loss: 0.3210 - accuracy: 0.8660
Epoch 8/100
3128/3128 [==============================] - 0s 52us/step - loss: 0.3140 - accuracy: 0.8686
Epoch 9/100
3128/3128 [==============================] - 0s 45us/step - loss: 0.3142 - accuracy: 0.8654
Epoch 10/100
3128/3128 [==============================] - 0s 48

3128/3128 [==============================] - 0s 94us/step - loss: 0.2025 - accuracy: 0.9194
Epoch 80/100
3128/3128 [==============================] - 0s 48us/step - loss: 0.2052 - accuracy: 0.9242
Epoch 81/100
3128/3128 [==============================] - 0s 51us/step - loss: 0.1983 - accuracy: 0.9287
Epoch 82/100
3128/3128 [==============================] - 0s 92us/step - loss: 0.1993 - accuracy: 0.9252
Epoch 83/100
3128/3128 [==============================] - 0s 75us/step - loss: 0.1917 - accuracy: 0.9290
Epoch 84/100
3128/3128 [==============================] - 0s 62us/step - loss: 0.2069 - accuracy: 0.9293
Epoch 85/100
3128/3128 [==============================] - 0s 72us/step - loss: 0.1971 - accuracy: 0.9258
Epoch 86/100
3128/3128 [==============================] - 0s 96us/step - loss: 0.2061 - accuracy: 0.9226
Epoch 87/100
3128/3128 [==============================] - 0s 59us/step - loss: 0.1991 - accuracy: 0.9277
Epoch 88/100
3128/3128 [==============================] - 0s 50us/st

### Testing the accuracy of the model on testing set

In [9]:
test_loss, test_acc = model.evaluate(X_test_new,  y_test, verbose=1)
print('\nTest Loss:', test_loss)
print('\nTest accuracy:', test_acc)

782/782 [==============================] - 0s 67us/step

Test Loss: 0.1915177945285807

Test accuracy: 0.9296675324440002


In [10]:
prediction_testy=model.predict_classes(X_test_new)
print('X_test\n',X_test_new)
print('Y_test\n',y_test)
# y_test.shape()

X_test
 [[0.000e+00 0.000e+00 0.000e+00 ... 1.833e+00 1.800e+01 9.350e+02]
 [0.000e+00 0.000e+00 0.000e+00 ... 3.222e+00 9.000e+00 2.900e+01]
 [0.000e+00 6.800e-01 1.360e+00 ... 4.281e+00 3.800e+01 1.370e+02]
 ...
 [2.300e-01 0.000e+00 2.300e-01 ... 4.022e+00 9.700e+01 5.430e+02]
 [0.000e+00 0.000e+00 0.000e+00 ... 2.000e+00 3.100e+01 1.560e+02]
 [3.200e-01 1.600e-01 1.600e-01 ... 6.586e+00 1.320e+02 9.550e+02]]
Y_test
 2793    0
2803    0
2218    1
3111    0
3161    0
       ..
1360    0
3759    0
2764    1
2389    1
807     1
Name: Y, Length: 782, dtype: int64


In [11]:
print('Predict\n', prediction_testy)

Predict
 [[0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 

### Save the model

In [12]:
import os
model.save('my_model_scaled')
# model.summary()

### Loading the dataset

In [13]:
df_pred=pd.read_csv("test_set.csv")
df_pred=df_pred.dropna()

X_pred=df_pred[['X1','X2','X3','X4','X5','X6','X7','X8','X9','X10','X11','X12','X13','X14','X15','X16','X17','X18','X19','X20','X21','X22','X23','X24','X25','X26','X27','X28','X29','X30','X1','X32','X33','X34','X35','X36','X37','X38','X39','X40','X41','X42','X43','X44','X45','X46','X47','X48','X49','X50','X51','X52','X53','X54','X55','X56','X57']]

X_pred_new=feature_select.transform(X_pred)
X_pred_new.shape


(691, 20)

### Make Predictions on the testing set

In [14]:
predictions = model.predict_classes(X_pred_new)

# X_pred.head()
print('Y=%s'%predictions)


Y=[[0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1